### ISSUE TITLE
Use latest PMD

### ISSUE THREAD

**Issue by sivakumar-kailasam** [sivakumar-kailasam/codeclimate-pmd#1]
Would be nice if we could have a script to do that where it can backup the current pmd folder and fetch the new one from the pmd repo's [releases](https://github.com/pmd/pmd/releases), run tests and remove the older one.

If not at least lets manually update it for now 😄

**Comment by rsoesemann** [comment]
What would we need for this to work. Just an URL were the latest RELEASE zips of PMD are uploaded?

**Comment by sivakumar-kailasam** [comment]
we would need to write a bash script which can perform the task mentioned in the issue

**Comment by sivakumar-kailasam** [comment]
Implemented
