### ISSUE TITLE
Update engines.json with all languages supported by PMD

### ISSUE THREAD

**Issue by sivakumar-kailasam** [sivakumar-kailasam/codeclimate-pmd#2]
Need to look through both [PMD](https://github.com/pmd/pmd) and [code climate spec](https://github.com/codeclimate/spec) update the [engines.json file](https://github.com/sivakumar-kailasam/codeclimate-pmd/blob/master/engine.json#L8) with the other supported languages.

**Comment by rsoesemann** [comment]
According to @adangel the maintainer of the PMD repo PMD is perfectly able to recognize which parser to apply by the file extensions.

**Comment by sivakumar-kailasam** [comment]
This is required for code climate for their needs.
