### ISSUE TITLE
Use PMD's official code climate adapter

### ISSUE THREAD

**Issue by sivakumar-kailasam** [sivakumar-kailasam/codeclimate-pmd#3]
PMD just made our lives simpler by adding a [Code climate adapter](https://github.com/pmd/pmd/blob/c9ff12785a8e19b02c9ac6cbadfcece8202b441c/src/site/markdown/usage/running.md.vm#L233). Lets start using that instead of the custom logic I wrote last year.

**Comment by rsoesemann** [comment]
This is the commit https://github.com/pmd/pmd/pull/83/commits/6d2b268ff61b14bf44bf21a19f0d4ef3ccbb2162 that added the CodeClimate renderer. Simply use another output format parameter in the PMD CLI.

I think we should enhance this code a bit (created issue in our fork https://github.com/Up2Go/pmd/issues/31) to allow people to add optional rule properties that we simply pass through to Code Climate. I am currently discussing with @adangel if and how this can be done.

**Comment by sivakumar-kailasam** [comment]
and done 😄
