### ISSUE TITLE
Add Up2Go as repo collaborators

### ISSUE THREAD

**Issue by rsoesemann** [sivakumar-kailasam/codeclimate-pmd#5]
@sivakumar-kailasam would you mind making me and @Up2Go-DavidRenz outside collaborators so we can directly contribute?

**Comment by sivakumar-kailasam** [comment]
would prefer to get things over via PRs to get started with. This repo might eventually be transferred to code climate org.

**Comment by sivakumar-kailasam** [comment]
@up2go-rsoesemann  To just add a little more context as to why I insist on PRs, 
- Not just me but all open source projects I know of welcome everyone to contribute and collaborate.
- Thanks to git, not everyone needs to have direct access to the main repo to contribute.
- I can understand if this is going to help @Up2Go-DavidRenz's thesis, but I still have to see contributions from him before I can make him a collaborator.

**Comment by rsoesemann** [comment]
I totally understand that. That's why we ended setting up our own repo and decided to make it Salesforce.com Apex specific. So we can learn from each other but not step on each other feet.
